# Copyright (c) 2021 Cisco and/or its affiliates.

# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at

#                https://developer.cisco.com/docs/licenses

# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

---
- name: Sample IOS playbook to run show commands
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: run show ip int brief
    cisco.ios.ios_command:
      commands: show ip interface brief
    register: myinterfaces

  - name: display value of "myinterfaces" variable
    debug:
      var: myinterfaces["stdout_lines"][0]

  - name: run show users
    cisco.ios.ios_command:
      commands: show users
    register: myusers

  - name: display value of "myusers" variable
    debug:
      var: myusers["stdout_lines"][0]